import type { MenuModuleI } from "@/interfaces/security";

export const MENU_MODULES_MOCK: MenuModuleI[] = [
  {
    id: "mod-parametros",
    name: "Parámetros",
    description: "Configuración de parámetros generales del sistema",
    route: "/parametros",
    order: 1,
    status: "Activo",
    categories: [
      {
        id: "cat-limites",
        moduleId: "mod-parametros",
        name: "Límites y Montos",
        description: "Administración de montos mínimos y máximos",
        route: "/parametros/limites",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-politicas",
        moduleId: "mod-parametros",
        name: "Políticas de Seguridad",
        description:
          "Configuración de vigencia de contraseña, tiempos, códigos",
        route: "/parametros/politicas",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-soft-token",
        moduleId: "mod-parametros",
        name: "Solicitud de Soft Token",
        description: "Configuración de solicitudes de soft token",
        route: "/parametros/soft-token",
        order: 3,
        status: "Activo",
      },
      {
        id: "cat-cuentas-origen",
        moduleId: "mod-parametros",
        name: "Cuentas de tipo de origen",
        description: "Configuración de tipos de cuentas de origen",
        route: "/parametros/cuentas-origen",
        order: 4,
        status: "Activo",
      },
      {
        id: "cat-cuentas-destino",
        moduleId: "mod-parametros",
        name: "Cuentas de tipo de destino",
        description: "Configuración de tipos de cuentas de destino",
        route: "/parametros/cuentas-destino",
        order: 5,
        status: "Inactivo",
      },
    ],
    subCategories: [
      {
        id: "subcat-seguridad",
        moduleId: "mod-parametros",
        name: "Seguridad",
        description: "Parámetros relacionados con la seguridad del sistema",
        order: 1,
        status: "Activo",
        menuIds: ["cat-politicas", "cat-soft-token"],
      },
    ],
  },
  {
    id: "mod-mantenimiento",
    name: "Mantenimiento de",
    description: "Módulo de mantenimiento y administración de entidades",
    route: "/mantenimiento",
    order: 2,
    status: "Activo",
    categories: [
      {
        id: "cat-red-transfer",
        moduleId: "mod-mantenimiento",
        name: "Red Transfer365",
        description: "Administración de participantes de Transfer365",
        route: "/mantenimiento/red-transfer365",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-corresponsales",
        moduleId: "mod-mantenimiento",
        name: "Corresponsales Financieros",
        description: "Gestión de preguntas de seguridad para corresponsales",
        route: "/mantenimiento/corresponsales",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-token",
        moduleId: "mod-mantenimiento",
        name: "Token",
        description: "Gestión de tokens de acceso",
        route: "/mantenimiento/token",
        order: 3,
        status: "Activo",
      },
      {
        id: "cat-atencion-soporte",
        moduleId: "mod-mantenimiento",
        name: "Atención y Soporte",
        description: "Herramientas de atención y soporte al cliente",
        route: "/mantenimiento/atencion-soporte",
        order: 1,
        status: "Activo",
        subCategoryId: "subcat-seguridad-soporte",
      },
      {
        id: "cat-cuestionario",
        moduleId: "mod-mantenimiento",
        name: "Cuestionario de Seguridad",
        description: "Gestión de preguntas de seguridad del sistema",
        route: "/mantenimiento/cuestionario-seguridad",
        order: 2,
        status: "Activo",
        subCategoryId: "subcat-seguridad-soporte",
      },
      {
        id: "cat-quejas",
        moduleId: "mod-mantenimiento",
        name: "Quejas y Reclamos",
        description: "Gestión de quejas y reclamos de clientes",
        route: "/mantenimiento/quejas-reclamos",
        order: 3,
        status: "Activo",
        subCategoryId: "subcat-seguridad-soporte",
      },
      {
        id: "cat-imagenes",
        moduleId: "mod-mantenimiento",
        name: "Imágenes de seguridad",
        description: "Repositorio de imágenes de seguridad del sistema",
        route: "/mantenimiento/imagenes-seguridad",
        order: 1,
        status: "Activo",
        subCategoryId: "subcat-multimedia",
      },
    ],
    subCategories: [
      {
        id: "subcat-seguridad-soporte",
        moduleId: "mod-mantenimiento",
        name: "Seguridad y soporte",
        description: "Herramientas de seguridad y soporte al cliente",
        order: 1,
        status: "Activo",
        menuIds: ["cat-atencion-soporte", "cat-cuestionario", "cat-quejas"],
      },
      {
        id: "subcat-multimedia",
        moduleId: "mod-mantenimiento",
        name: "Multimedia",
        description: "Gestión de recursos multimedia del sistema",
        order: 2,
        status: "Activo",
        menuIds: ["cat-imagenes"],
      },
    ],
  },
  {
    id: "mod-reportes",
    name: "Reportes",
    description: "Generación y consulta de reportes operativos",
    route: "/reportes",
    order: 3,
    status: "Activo",
    categories: [
      {
        id: "cat-reportes-internos",
        moduleId: "mod-reportes",
        name: "Reportes Internos",
        description: "Reportes internos del sistema",
        route: "/reportes/internos",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-transfer365",
        moduleId: "mod-reportes",
        name: "Transfer365",
        description: "Reportes de transferencias 365",
        route: "/reportes/transfer365",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-recurrentes",
        moduleId: "mod-reportes",
        name: "Recurrentes",
        description: "Reportes de pagos recurrentes",
        route: "/reportes/recurrentes",
        order: 3,
        status: "Activo",
      },
      {
        id: "cat-servicios-eventos",
        moduleId: "mod-reportes",
        name: "Servicios/Eventos",
        description: "Reportes de servicios y eventos",
        route: "/reportes/servicios-eventos",
        order: 4,
        status: "Activo",
      },
      {
        id: "cat-corresponsales-fin",
        moduleId: "mod-reportes",
        name: "Corresponsales Financieros",
        description: "Reportes de corresponsales financieros",
        route: "/reportes/corresponsales-financieros",
        order: 5,
        status: "Activo",
      },
    ],
    subCategories: [],
  },
  {
    id: "mod-gestiones",
    name: "Gestiones",
    description: "Gestión de operaciones y solicitudes del sistema",
    route: "/gestiones",
    order: 4,
    status: "Activo",
    categories: [
      {
        id: "cat-gest-corresponsales",
        moduleId: "mod-gestiones",
        name: "Corresponsales",
        description: "Gestión de corresponsales",
        route: "/gestiones/corresponsales",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-reclamos",
        moduleId: "mod-gestiones",
        name: "Reclamos",
        description: "Gestión de reclamos",
        route: "/gestiones/reclamos",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-transacciones",
        moduleId: "mod-gestiones",
        name: "Transacciones",
        description: "Gestión de transacciones",
        route: "/gestiones/transacciones",
        order: 3,
        status: "Activo",
      },
    ],
    subCategories: [],
  },
  {
    id: "mod-usuarios",
    name: "Usuarios",
    description: "Administración de usuarios y notificaciones",
    route: "/usuarios",
    order: 5,
    status: "Activo",
    categories: [
      {
        id: "cat-soporte-usuarios",
        moduleId: "mod-usuarios",
        name: "Soporte a usuarios",
        description: "Herramientas de soporte a usuarios",
        route: "/usuarios/soporte",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-consulta-usuarios",
        moduleId: "mod-usuarios",
        name: "Consulta de usuarios",
        description: "Consulta de información de usuarios",
        route: "/usuarios/consulta",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-notificaciones",
        moduleId: "mod-usuarios",
        name: "Envío de notificaciones",
        description: "Envío de notificaciones a usuarios",
        route: "/usuarios/notificaciones",
        order: 3,
        status: "Activo",
      },
    ],
    subCategories: [],
  },
  {
    id: "mod-seguridad",
    name: "Seguridad",
    description: "Gestión de seguridad, roles, grupos y permisos",
    route: "/seguridad",
    order: 6,
    status: "Activo",
    categories: [
      {
        id: "cat-seg-usuarios",
        moduleId: "mod-seguridad",
        name: "Usuarios",
        description: "Gestión de usuarios del sistema",
        route: "/seguridad/usuarios",
        order: 1,
        status: "Activo",
      },
      {
        id: "cat-grupos",
        moduleId: "mod-seguridad",
        name: "Grupos",
        description: "Gestión de grupos de usuarios",
        route: "/seguridad/grupos",
        order: 2,
        status: "Activo",
      },
      {
        id: "cat-roles",
        moduleId: "mod-seguridad",
        name: "Roles",
        description: "Gestión de roles del sistema",
        route: "/seguridad/roles",
        order: 3,
        status: "Activo",
      },
      {
        id: "cat-roles-grupo",
        moduleId: "mod-seguridad",
        name: "Roles por grupo",
        description: "Asignación de roles por grupo",
        route: "/seguridad/roles-por-grupo",
        order: 4,
        status: "Activo",
      },
      {
        id: "cat-usuarios-rol",
        moduleId: "mod-seguridad",
        name: "Usuarios por rol",
        description: "Consulta de usuarios por rol",
        route: "/seguridad/usuarios-por-rol",
        order: 5,
        status: "Activo",
      },
      {
        id: "cat-menu",
        moduleId: "mod-seguridad",
        name: "Menú",
        description: "Gestión de menús del sistema",
        route: "/seguridad/menu",
        order: 6,
        status: "Activo",
      },
    ],
    subCategories: [],
  },
];
