import type { SecurityUserI, EmployeeSearchResultI } from "@/interfaces/security";

export const SECURITY_USERS_MOCK: SecurityUserI[] = [
  {
    id: "u001",
    employeeNumber: "EMP001",
    fullName: "Carlos Martínez López",
    email: "carlos.martinez@comedica.com.sv",
    username: "carlos.martinez",
    office: "Oficina Central",
    costCenter: "CC-001",
    roles: ["Administrador"],
    groups: ["Grupo Admin"],
    lastLogin: "2025-01-15T10:30:00Z",
    status: "activo",
    phone: "7890-1234",
    documentType: "DUI",
    documentNumber: "12345678-9",
  },
  {
    id: "u002",
    employeeNumber: "EMP002",
    fullName: "María Elena Ramírez Flores",
    email: "maria.ramirez@comedica.com.sv",
    username: "maria.ramirez",
    office: "Sucursal Norte",
    costCenter: "CC-002",
    roles: ["Analista"],
    groups: ["Grupo Analistas"],
    lastLogin: "2025-01-14T15:20:00Z",
    status: "activo",
    phone: "7891-2345",
    documentType: "DUI",
    documentNumber: "01234567-8",
  },
  {
    id: "u003",
    employeeNumber: "EMP003",
    fullName: "Juan Pablo Flores Mendoza",
    email: "juan.flores@comedica.com.sv",
    username: "juan.flores",
    office: "Sucursal Sur",
    costCenter: "CC-003",
    roles: ["Operador"],
    groups: ["Grupo Operadores"],
    lastLogin: "2025-01-10T09:00:00Z",
    status: "bloqueado",
    phone: "7892-3456",
    documentType: "DUI",
    documentNumber: "02345678-9",
  },
  {
    id: "u004",
    employeeNumber: "EMP004",
    fullName: "Ana Sofía Recinos Castro",
    email: "ana.recinos@comedica.com.sv",
    username: "ana.recinos",
    office: "Oficina Central",
    costCenter: "CC-001",
    roles: ["Supervisor"],
    groups: ["Grupo Supervisores"],
    lastLogin: "2025-01-15T08:45:00Z",
    status: "activo",
    phone: "7893-4567",
    documentType: "DUI",
    documentNumber: "03456789-0",
  },
  {
    id: "u005",
    employeeNumber: "EMP005",
    fullName: "Roberto Antonio Vásquez Díaz",
    email: "roberto.vasquez@comedica.com.sv",
    username: "roberto.vasquez",
    office: "Sucursal Este",
    costCenter: "CC-004",
    roles: ["Analista"],
    groups: ["Grupo Analistas"],
    lastLogin: "2025-01-13T14:10:00Z",
    status: "activo",
    phone: "7894-5678",
    documentType: "DUI",
    documentNumber: "04567890-1",
  },
];

export const EMPLOYEES_MOCK: EmployeeSearchResultI[] = [
  {
    employeeNumber: "EMP006",
    nombres: "Pedro",
    apellidos: "García Pérez",
    cargo: "Analista Financiero",
    oficina: "Oficina Central",
    centroCostos: "CC-001",
    tipoDocumento: "DUI",
    numeroDocumento: "05678901-2",
  },
  {
    employeeNumber: "EMP007",
    nombres: "Lucía",
    apellidos: "Hernández Molina",
    cargo: "Supervisora de Créditos",
    oficina: "Sucursal Norte",
    centroCostos: "CC-002",
    tipoDocumento: "DUI",
    numeroDocumento: "06789012-3",
  },
  {
    employeeNumber: "EMP008",
    nombres: "Diego",
    apellidos: "Ramírez Castillo",
    cargo: "Operador de Sistemas",
    oficina: "Sucursal Sur",
    centroCostos: "CC-003",
    tipoDocumento: "DUI",
    numeroDocumento: "07890123-4",
  },
];
