// ==================== ATENCIÓN Y SOPORTE ====================
let supportReasons = [
  {
    id: 'SOP-001',
    code: 'SOP-001',
    description: 'Problemas de acceso a la banca en línea',
    hasQuestionnaire: true,
    questions: 4,
    failures: 2,
    status: 'Activo',
    createdAt: '2025-11-15T10:00:00Z',
    createdBy: 'Admin',
    updatedAt: '2026-01-10T14:30:00Z',
    updatedBy: 'Gerente TI',
  },
  {
    id: 'SOP-002',
    code: 'SOP-002',
    description: 'Bloqueo de usuario por intentos fallidos',
    hasQuestionnaire: true,
    questions: 3,
    failures: 1,
    status: 'Activo',
    createdAt: '2025-11-20T09:00:00Z',
    createdBy: 'Admin',
    updatedAt: '2026-01-05T11:20:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'SOP-003',
    code: 'SOP-003',
    description: 'Solicitud de reposición de tarjeta',
    hasQuestionnaire: false,
    questions: 0,
    failures: 0,
    status: 'Activo',
    createdAt: '2025-12-01T08:00:00Z',
    createdBy: 'Manager',
    updatedAt: '2025-12-01T08:00:00Z',
    updatedBy: 'Manager',
  },
  {
    id: 'SOP-004',
    code: 'SOP-004',
    description: 'Consulta de saldo no disponible',
    hasQuestionnaire: false,
    questions: 0,
    failures: 0,
    status: 'Inactivo',
    createdAt: '2025-10-10T10:00:00Z',
    createdBy: 'System',
    updatedAt: '2025-12-20T16:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'SOP-005',
    code: 'SOP-005',
    description: 'Error en transferencia interbancaria',
    hasQuestionnaire: true,
    questions: 5,
    failures: 2,
    status: 'Activo',
    createdAt: '2025-11-25T12:00:00Z',
    createdBy: 'Admin',
    updatedAt: '2026-01-15T09:45:00Z',
    updatedBy: 'Gerente TI',
  },
];

// ==================== CUESTIONARIO DE SEGURIDAD ====================
let securityQuestions = [
  {
    id: 'Q001',
    code: '0001',
    question: '¿Cuál es tu fecha de nacimiento?',
    status: 'Activo',
    createdBy: 'Admin',
    createdAt: '2024-06-15T10:00:00Z',
    modifiedBy: 'Admin',
    modifiedAt: '2026-01-12T12:00:00Z',
  },
  {
    id: 'Q002',
    code: '0002',
    question: '¿Cuál es el nombre de tu mascota?',
    status: 'Activo',
    createdBy: 'System',
    createdAt: '2024-08-20T14:30:00Z',
    modifiedBy: 'Admin',
    modifiedAt: '2024-10-12T10:00:00Z',
  },
  {
    id: 'Q003',
    code: '0003',
    question: '¿En qué ciudad naciste?',
    status: 'Activo',
    createdBy: 'System',
    createdAt: '2024-09-10T09:00:00Z',
    modifiedBy: 'System',
    modifiedAt: '2024-11-12T11:00:00Z',
  },
  {
    id: 'Q004',
    code: '0003',
    question: '¿Cuál es el nombre de tu mejor amigo de la infancia?',
    status: 'Activo',
    createdBy: 'Admin',
    createdAt: '2024-07-05T11:00:00Z',
    modifiedBy: 'Admin',
    modifiedAt: '2024-09-12T13:00:00Z',
  },
  {
    id: 'Q005',
    code: '0004',
    question: '¿Cuál es tu color favorito?',
    status: 'Inactivo',
    createdBy: 'Manager',
    createdAt: '2024-05-10T08:00:00Z',
    modifiedBy: 'Manager',
    modifiedAt: '2024-12-01T10:00:00Z',
  },
];

// ==================== IMÁGENES ====================
let securityImages = [
  {
    id: 'IMG-001',
    name: 'Escudo Protector',
    type: 'mobile',
    filename: 'escudo_protector.png',
    uploadedAt: '2025-12-01T10:00:00Z',
    uploadedBy: 'Sistema',
    size: '256 KB',
    dimensions: '1080x1920',
    url: '/images/security/escudo_protector.png',
  },
  {
    id: 'IMG-002',
    name: 'Soporte quejas y sugerencias',
    type: 'mobile',
    filename: 'soporte_quejas.png',
    uploadedAt: '2025-12-01T12:00:00Z',
    uploadedBy: 'Gerente TI',
    size: '312 KB',
    dimensions: '1080x1920',
    url: '/images/security/soporte_quejas.png',
  },
  {
    id: 'IMG-003',
    name: 'Escudo Protector',
    type: 'desktop',
    filename: 'escudo_protector_desktop.png',
    uploadedAt: '2025-12-01T10:05:00Z',
    uploadedBy: 'María Rodríguez',
    size: '512 KB',
    dimensions: '1920x1080',
    url: '/images/security/escudo_protector_desktop.png',
  },
  {
    id: 'IMG-004',
    name: 'Soporte quejas y sugerencias',
    type: 'desktop',
    filename: 'soporte_quejas_desktop.png',
    uploadedAt: '2025-11-01T14:00:00Z',
    uploadedBy: 'María Rodríguez',
    size: '450 KB',
    dimensions: '1920x1080',
    url: '/images/security/soporte_quejas_desktop.png',
  },
];

// ==================== CATÁLOGO DE PRODUCTOS ====================
let productCatalog = [
  {
    id: 'PROD-001',
    code: 'AHO-001',
    name: 'Cuenta de Ahorro Personal',
    description: 'Cuenta de ahorro para personas individuales con beneficios y tasas preferenciales',
    status: 'Activo',
    category: 'Ahorros',
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'Sistema',
    updatedAt: '2025-06-10T14:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'PROD-002',
    code: 'COR-001',
    name: 'Cuenta Corriente Empresarial',
    description: 'Cuenta corriente diseñada para empresas con chequera y banca en línea',
    status: 'Activo',
    category: 'Corriente',
    createdAt: '2024-02-20T09:00:00Z',
    createdBy: 'Admin',
    updatedAt: '2025-08-15T11:00:00Z',
    updatedBy: 'Gerente Productos',
  },
  {
    id: 'PROD-003',
    code: 'TDC-001',
    name: 'Tarjeta de Crédito Gold',
    description: 'Tarjeta de crédito con beneficios exclusivos y puntos de recompensa',
    status: 'Activo',
    category: 'Tarjetas',
    createdAt: '2024-03-10T11:00:00Z',
    createdBy: 'Gerente Productos',
    updatedAt: '2025-09-20T10:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'PROD-004',
    code: 'PRE-001',
    name: 'Préstamo Personal',
    description: 'Préstamo personal con tasas competitivas y plazos flexibles',
    status: 'Activo',
    category: 'Préstamos',
    createdAt: '2024-04-05T08:00:00Z',
    createdBy: 'Sistema',
    updatedAt: '2025-11-05T13:00:00Z',
    updatedBy: 'Admin',
  },
  {
    id: 'PROD-005',
    code: 'INV-001',
    name: 'Depósito a Plazo Fijo',
    description: 'Inversión a plazo fijo con tasas de interés garantizadas',
    status: 'Inactivo',
    category: 'Inversiones',
    createdAt: '2024-05-15T12:00:00Z',
    createdBy: 'Gerente Productos',
    updatedAt: '2025-12-01T09:00:00Z',
    updatedBy: 'Admin',
  },
];

// ==================== AUDITORÍA DE MANTENIMIENTO ====================
let maintenanceAuditLog = [
  {
    id: 'MAINT-AUD-001',
    userId: 'admin-001',
    userName: 'Admin',
    userRole: 'Administrador',
    action: 'Creación de motivo de soporte',
    module: 'Atención y Soporte',
    details: 'Motivo: Problemas de acceso a la banca en línea',
    changes: [
      { field: 'Estado', oldValue: 'N/A', newValue: 'Activo' },
    ],
    timestamp: '2026-01-15T10:00:00Z',
  },
  {
    id: 'MAINT-AUD-002',
    userId: 'ti-001',
    userName: 'Gerente TI',
    userRole: 'Gerente TI',
    action: 'Actualización de pregunta de seguridad',
    module: 'Cuestionario de Seguridad',
    details: 'Pregunta: ¿Cuál es tu fecha de nacimiento?',
    changes: [
      { field: 'Estado', oldValue: 'Inactivo', newValue: 'Activo' },
    ],
    timestamp: '2026-01-12T12:00:00Z',
  },
  {
    id: 'MAINT-AUD-003',
    userId: 'system-001',
    userName: 'Sistema',
    userRole: 'Sistema',
    action: 'Carga de nueva versión mobile',
    module: 'Imágenes de seguridad',
    details: 'Imagen Mobile: Escudo Protector',
    changes: [
      { field: 'Imagen', oldValue: 'imagen_antigua.png', newValue: 'imagen_nueva.png' },
    ],
    timestamp: '2025-12-01T04:27:00Z',
  },
  {
    id: 'MAINT-AUD-004',
    userId: 'admin-001',
    userName: 'Admin',
    userRole: 'Administrador',
    action: 'Actualización de producto',
    module: 'Catálogo de productos',
    details: 'Producto: Cuenta de Ahorro Personal',
    changes: [
      { field: 'Descripción', oldValue: 'Descripción antigua', newValue: 'Cuenta de ahorro para personas individuales con beneficios' },
    ],
    timestamp: '2025-06-10T14:00:00Z',
  },
];

module.exports = {
  supportReasons,
  securityQuestions,
  securityImages,
  productCatalog,
  maintenanceAuditLog,
};
